//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ICSheet5e.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ICSheet5e.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;BasicArmors&gt;
        ///  &lt;Armor Name=&quot;Padded&quot; ArmorType=&quot;Light&quot;&gt;
        ///    &lt;Cost&gt;5&lt;/Cost&gt;
        ///    &lt;ArmorClass&gt;11&lt;/ArmorClass&gt;
        ///    &lt;Weight&gt;8&lt;/Weight&gt;
        ///    &lt;Properties&gt;Disadvantage on Stealth checks.&lt;/Properties&gt;
        ///  &lt;/Armor&gt;
        ///  &lt;Armor Name=&quot;Leather&quot; ArmorType=&quot;Light&quot;&gt;
        ///    &lt;Cost&gt;10&lt;/Cost&gt;
        ///    &lt;ArmorClass&gt;11&lt;/ArmorClass&gt;
        ///    &lt;Weight&gt;10&lt;/Weight&gt;
        ///    &lt;Properties&gt;&lt;/Properties&gt;
        ///  &lt;/Armor&gt;
        ///  &lt;Armor Name=&quot;Studded leather&quot; ArmorType=&quot;Light&quot;&gt;
        ///    &lt;Cost&gt;45&lt;/Cost&gt;
        ///    &lt;ArmorClass&gt;12&lt;/Arm [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string BasicArmors {
            get {
                return ResourceManager.GetString("BasicArmors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;BasicItems&gt;
        ///&lt;/BasicItems&gt;.
        /// </summary>
        internal static string BasicItems {
            get {
                return ResourceManager.GetString("BasicItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;BasicWeapons&gt;
        ///  &lt;Weapon Name=&quot;Club&quot; Category=&quot;SimpleMelee&quot;&gt;
        ///    &lt;Cost&gt;0.1&lt;/Cost&gt;
        ///    &lt;Damage&gt;1d4&lt;/Damage&gt;
        ///    &lt;DamageType&gt;Bludgeoning&lt;/DamageType&gt;
        ///    &lt;Weight&gt;2&lt;/Weight&gt;
        ///    &lt;Properties&gt;Light&lt;/Properties&gt;
        ///  &lt;/Weapon&gt;
        ///  &lt;Weapon Name=&quot;Dagger&quot; Category=&quot;SimpleMelee&quot;&gt;
        ///    &lt;Cost&gt;2&lt;/Cost&gt;
        ///    &lt;Damage&gt;1d4&lt;/Damage&gt;
        ///    &lt;DamageType&gt;Piercing&lt;/DamageType&gt;
        ///    &lt;Weight&gt;1&lt;/Weight&gt;
        ///    &lt;Properties&gt;Finesse, Light, thrown (20/60)&lt;/Properties&gt;
        ///  &lt;/Weapon&gt;
        ///  &lt;Weapon Nam [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string BasicWeapons {
            get {
                return ResourceManager.GetString("BasicWeapons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;ClassFeatures&gt;
        ///  &lt;PCClass Name=&quot;Barbarian&quot;&gt;
        ///    &lt;Feature Name=&quot;Hit Dice&quot;&gt;d12&lt;/Feature&gt;
        ///    &lt;Feature Name=&quot;Hit Points&quot;&gt;12 + CON; 1d12 (7) + CON after 1st&lt;/Feature&gt;
        ///    &lt;Feature Name=&quot;Armor Proficiencies&quot;&gt;Light, Medium, Shields&lt;/Feature&gt;
        ///    &lt;Feature Name=&quot;Weapon Proficiencies&quot;&gt;Simple, martial&lt;/Feature&gt;
        ///    &lt;Feature Name=&quot;Tool Proficiencies&quot;&gt;None&lt;/Feature&gt;
        ///    &lt;Feature Name=&quot;Rage&quot;&gt;Advantage on STR checks/saving throws. Bonus Damage (see table) on STR weapon att [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ClassFeatures {
            get {
                return ResourceManager.GetString("ClassFeatures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap inventory_background {
            get {
                object obj = ResourceManager.GetObject("inventory_background", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;FeatureSet&gt;
        ///  &lt;Race Name=&quot;Dwarf&quot;&gt;
        ///    &lt;Feature Name=&quot;Ability Bonus&quot;&gt;+2 CON&lt;/Feature&gt;
        ///    &lt;Feature Name=&quot;Speed&quot;&gt;Your speed is not reduced by wearing heavy armor.&lt;/Feature&gt;
        ///    &lt;Feature Name=&quot;Vision&quot;&gt;Darkvision: 60ft&lt;/Feature&gt;
        ///    &lt;Feature Name=&quot;Dwarven Resilience&quot;&gt;Advantage on saves vs poison and resistance to poison damage.&lt;/Feature&gt;
        ///    &lt;Feature Name=&quot;Dwarven Combat Training&quot;&gt;You have proficiency with battleaxe, handaxe, light hammer, and warhammer.&lt;/Feature&gt; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string RacialFeatures {
            get {
                return ResourceManager.GetString("RacialFeatures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;SpellList&gt;
        ///&lt;CastingClass Name=&quot;bard&quot;&gt;
        ///&lt;Spell Name=&quot;Animal Messenger&quot;/&gt;
        ///&lt;Spell Name=&quot;Animate Objects&quot;/&gt;
        ///&lt;Spell Name=&quot;Awaken&quot;/&gt;
        ///&lt;Spell Name=&quot;Bane&quot;/&gt;
        ///&lt;Spell Name=&quot;Bestow Curse&quot;/&gt;
        ///&lt;Spell Name=&quot;Blindness/Deafness&quot;/&gt;
        ///&lt;Spell Name=&quot;Calm Emotions&quot;/&gt;
        ///&lt;Spell Name=&quot;Charm Person&quot;/&gt;
        ///&lt;Spell Name=&quot;Clairvoyance&quot;/&gt;
        ///&lt;Spell Name=&quot;Comprehend Languages&quot;/&gt;
        ///&lt;Spell Name=&quot;Compulsion&quot;/&gt;
        ///&lt;Spell Name=&quot;Confusion&quot;/&gt;
        ///&lt;Spell Name=&quot;Cure Wounds&quot;/&gt;
        ///&lt;Spell Name=&quot;Dancing Lights&quot;/&gt;
        ///&lt;Spell [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string spell_list {
            get {
                return ResourceManager.GetString("spell_list", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [
        ///    {
        ///        &quot;Range&quot;: &quot;90 feet&quot;,
        ///        &quot;name&quot;: &quot;Acid Arrow&quot;,
        ///        &quot;school&quot;: &quot;evocation&quot;,
        ///        &quot;Duration&quot;: &quot;Instantaneous&quot;,
        ///        &quot;Components&quot;: &quot;V, S, M (powdered rhubarb leaf and an adder&apos;s stomach)&quot;,
        ///        &quot;Casting Time&quot;: &quot;1 action&quot;,
        ///        &quot;text&quot;: &quot;A shimmering green arrow streaks toward a target within range and bursts in a spray of acid. Make a ranged spell attack against the target. On a hit, the target takes 4d4 acid damage immediately and 2d4 acid damage at the end of its next [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SpellList5e {
            get {
                return ResourceManager.GetString("SpellList5e", resourceCulture);
            }
        }
    }
}
