//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ICSheetCore.Properties {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ICSheetCore.Properties.Resources", typeof(Resources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BasicArmors.xml.
        /// </summary>
        internal static string ArmorItemPath {
            get {
                return ResourceManager.GetString("ArmorItemPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ClassFeatures.xml.
        /// </summary>
        internal static string ClassFeaturesPath {
            get {
                return ResourceManager.GetString("ClassFeaturesPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RacialFeatures.xml.
        /// </summary>
        internal static string RacialFeaturesPath {
            get {
                return ResourceManager.GetString("RacialFeaturesPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SpellList5e.json.
        /// </summary>
        internal static string SpellDetailsPath {
            get {
                return ResourceManager.GetString("SpellDetailsPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to spell_list.xml.
        /// </summary>
        internal static string SpellNamesPath {
            get {
                return ResourceManager.GetString("SpellNamesPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BasicWeapons.xml.
        /// </summary>
        internal static string WeaponItemPath {
            get {
                return ResourceManager.GetString("WeaponItemPath", resourceCulture);
            }
        }
    }
}
